defaults: &defaults
  fog_provider: 'AWS'
  aws_access_key_id: 'AKIAYL3CRL44WZIIAON4'
  aws_secret_access_key: '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'
  # To use AWS reduced redundancy storage.
  # aws_reduced_redundancy: true
  fog_directory: "touchapp-rails-bucket"
  # You may need to specify what region your storage bucket is in
  # fog_region: "eu-west-1"
  existing_remote_files: keep
  # To delete existing remote files.
  # existing_remote_files: delete
  # Automatically replace files with their equivalent gzip compressed version
  # gzip_compression: true
  # Fail silently.  Useful for environments such as Heroku
  # fail_silently: true

development:
  <<: *defaults
  enabled: false

test:
  <<: *defaults
  enabled: false

production:
  <<: *defaults
  fog_directory: "touchapp-rails-bucket"
